env:
  browser: true
  es6: true
  node: true
extends:
  - 'plugin:vue/essential'
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - vue
rules:
  consistent-return: off
  default-case: off
  quote-props: off
  no-console: off
  no-continue: off
  no-plusplus: off
  no-return-assign: off
  object-curly-newline: off
