const fs = require('fs');
const { execSync } = require('child_process');

const apiRoot = `${__dirname}/../api`;

const routes = execSync(`find ${apiRoot} -type f`)
  .toString()
  .split('\n')
  .filter(Boolean)
  .filter((path) => path.endsWith('/infos.json'))
  .map((path) => path.substring(0, path.lastIndexOf('/')))
  .map((path) => path.substring(apiRoot.length));

const lines = [];
lines.push('// File generated by routes.builder.js');
lines.push('/* eslint-disable global-require */');
lines.push('module.exports = [');
routes.forEach((route) => {
  lines.push('  {');
  lines.push(`    path: '${route}',`);
  lines.push(`    infos: require('../api${route}/infos'),`);
  lines.push(`    controller: require('../api${route}/controller'),`);
  try {
    fs.accessSync(`${apiRoot + route}/schema.json`);
    lines.push(`    schema: require('../api${route}/schema'),`);
  } catch (e) { /* */ }
  lines.push('  },');
});
lines.push('];');
lines.push('');

fs.writeFileSync(`${__dirname}/routes.js`, lines.join('\n'));
